# Generated by Django 4.1.2 on 2022-10-17 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='Progress',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
